# Generated by Django 3.2 on 2025-07-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erNumber', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('permanentAddress', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobilePhone', models.CharField(blank=True, max_length=20)),
                ('alternativeNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('guardianName', models.CharField(blank=True, max_length=255, null=True)),
                ('referredBy', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorName', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
